import "./styles.scss";

function LovePixelMath(props) {
  return (
    <div className="row mt-5 h-backgound-image">
      <div id="carouselExampleControls" className="carousel slide pixel-card"  data-interval="3000" data-ride="carousel">
        <div className="carousel-inner">
          <div className="carousel-item active">
            <div className="d-flex justify-content-center">
              <div className="col-sm-10 shadow slider-card-sec-4">
                <center> <h2 className="font-weight-bold mt-4"> People Love PixelMath</h2></center>
                <div className="d-flex flex-column justify-content-center">
                  <div className="row p-4 m-2">
                    <div className="col-sm-4">
                      <h5 className="font-weight-bold">Abhishek Thakur</h5>
                      <p>Parent</p>
                    </div>
                    <div className="col-sm-8">
                      PixelMath has made learning maths even more fun for my child.
                      The reports generated by the app are very useful to gauge my
                      child’s progress.
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="carousel-item">
            <div className="d-flex justify-content-center">
              <div className="col-sm-10 shadow slider-card-sec-4">
                <center> <h2 className="font-weight-bold mt-4"> People Love PixelMath</h2></center>
                <div className="d-flex flex-column justify-content-center">
                  <div className="row p-4 m-2">
                    <div className="col-sm-4">
                      <h5 className="font-weight-bold">Ajay Udayan</h5>
                      <p>Parent</p>
                    </div>
                    <div className="col-sm-8">
                      PixelMath has made learning maths even more fun for my child
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="carousel-item">
            <div className="d-flex justify-content-center">
              <div className="col-sm-10 shadow slider-card-sec-4">
                <center> <h2 className="font-weight-bold mt-4"> People Love PixelMath</h2></center>
                <div className="d-flex flex-column justify-content-center">
                  <div className="row p-4 m-2">
                    <div className="col-sm-4">
                      <h5 className="font-weight-bold">Anoop Gupta</h5>
                      <p>Parent</p>
                    </div>
                    <div className="col-sm-8">
                      PixelMath has made learning maths even more fun for my child.
                      The reports generated by the
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <a className="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span className="carousel-control-prev-icon slider-arrow" aria-hidden="true"></span>
        </a>
        <a className="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span className="carousel-control-next-icon slider-arrow" aria-hidden="true"></span>
        </a>
      </div>
    </div>
  )
}

export default LovePixelMath;